# name: Deploy Vercel Production

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     if: "!contains(github.event.head_commit.message, '[skip ci]')"
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Deploy to Vercel Action
#         uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           github-token: ${{ secrets.GH_TOKEN }}
#           vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#           vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
